######################################################
################# Setup Elasticsearch ################
######################################################
---

- name: Copy Files
  copy:
    src: "{{ item }}"
    dest: "{{ elastic_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - elastic-namespace.yml
    - elasticsearch-discovery-service.yml
    - elasticsearch-cluster-ip-service.yml
    - Dockerfile
    - custom-entrypoint
    - log4j2.properties

- name: Install Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ elastic_dir }}/{{ item }}"
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
  with_items:
    - elasticsearch-definition.yml

- name: 'Build Kafka container'
  docker_image:
    name: 'rocknsm/kafka'
    pull: yes
    state: present
    path: "{{ elastic_dir }}/"
    dockerfile: 'Dockerfile'

- name: Create Config
  shell: kubectl create -f elasticsearch.yml
  register: debug_output

- name: Debug Output
  debug:
    msg:
      - "Command is: {{ debug_output.cmd }}"
      - "Stdout is: {{ debug_output.stdout }}"
  when: debug_enabled is defined and debug_enabled and debug_output.stdout is defined

- name: Create Config
  shell: kubectl create -f es-discovery-svc.yml
  register: debug_output

- name: Debug Output
  debug:
    msg:
      - "Command is: {{ debug_output.cmd }}"
      - "Stdout is: {{ debug_output.stdout }}"
  when: debug_enabled is defined and debug_enabled and debug_output.stdout is defined

- name: Create Config
  shell: kubectl create -f elasticsearch-cluster-ip-service.yml
  register: debug_output

- name: Debug Output
  debug:
    msg:
      - "Command is: {{ debug_output.cmd }}"
      - "Stdout is: {{ debug_output.stdout }}"
  when: debug_enabled is defined and debug_enabled and debug_output.stdout is defined

- name: Create Config
  shell: kubectl create -f elasticsearch-loadbalancer-service.yml
  register: debug_output

- name: Debug Output
  debug:
    msg:
      - "Command is: {{ debug_output.cmd }}"
      - "Stdout is: {{ debug_output.stdout }}"
  when: debug_enabled is defined and debug_enabled and debug_output.stdout is defined

- name: Create Config
  shell: kubectl create -f elasticsearch.yml
  register: debug_output

- name: Debug Output
  debug:
    msg:
      - "Command is: {{ debug_output.cmd }}"
      - "Stdout is: {{ debug_output.stdout }}"
  when: debug_enabled is defined and debug_enabled and debug_output.stdout is defined

#- name: Wait for Elasticsearch to be ready
#  shell: |
#    while [ "$(kubectl get pods | grep es-master | head -n +1 | awk '{ print $2}')" != "1/1" ]; do
#      echo -n .;
#      sleep 1;
#    done;
