%YAML 1.1
---

#### Kibana configuration variables ####

# Add in the custom rock dashboards
rock_dashboards_repo: https://github.com/rocknsm/rock-dashboards.git
rock_dashboards_branch: master
rock_dashboards_url: "https://github.com/rocknsm/rock-dashboards/archive/{{ rock_dashboards_branch }}.tar.gz"
rock_dashboards_filename: "rock-dashboards_{{ rock_dashboards_branch | replace('/', '-') }}.tar.gz"
rock_dashboards_version: 2.0

es_url: "http://rock-elasticsearch:9200"
es_url_external: "http://rockserver1:9200"

# Which image version of Kibana this role is using.
kibana_ver: "{{ elastic_ver }}"
kibana_port: '5601'
kibana_ip: '0.0.0.0'
kibana_image: 'docker.elastic.co/kibana/kibana'
kibana_container_name: 'rock-kibana'
kibana_yum: 'kibana'

kibana_dir: "{{ rocknsm_dir }}/kibana"
kibana_dashboard_dir: "{{ rocknsm_dir }}/kibana/dashboards"
...
