# The Cluster-IP service will expose the Elasticsearch cluster on a
# cluster-internal IP, that is only reachable from within the Kubernetes cluster.

apiVersion: v1
kind: Service
metadata:
  name: es-ia-svc
  labels:
    app: es-ia-svc
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
 
