---
#- name: Deploy GlusterFS Daemonset
#  shell: |
#    kubectl create -f {{ gluster_dir }}/glusterfs-daemonset.json
#    GLUSTER_WANTED=$(kubectl get -f {{ gluster_dir }}/glusterfs-daemonset.json --no-headers=true | awk '{ print $2}')
#    while [ $(kubectl get -f {{ gluster_dir }}/glusterfs-daemonset.json --no-headers=true | awk '{ print $4}') != $GLUSTER_WANTED ]; do
#      echo -n .;
#      sleep 1;
#    done;

- name: Gluster | Deploy Daemonset
  command: "kubectl create -f {{ gluster_dir }}/glusterfs-daemonset.json"
  register: gluster_deploy_daemonset_result

- name: Gluster | Wait for daemonset
  shell: |
     if [ $(kubectl get ds glusterfs -o jsonpath={.status.desiredNumberScheduled}) \
     == $(kubectl get ds glusterfs -o jsonpath={.status.numberReady}) ]; then
       echo "ready";
     fi;
  register: ds_not_ready
  until: ds_not_ready.stdout=='ready'
  retries: 30
  delay: 15
  ignore_errors: yes
  when: gluster_deploy_daemonset_result.rc == 0

- name: Create Service Account
  shell: kubectl create -f {{ gluster_dir }}/heketi-service-account.json
  register: heketi_service_account_result

- name: Gluster | Wait for daemonset
  shell: "kubectl get sa heketi-service-account --no-headers=true | awk '{ print $1 }'"
  register: ds_not_ready
  until: ds_not_ready.stdout=='heketi-service-account'
  retries: 10
  delay: 5
  ignore_errors: yes
  when: heketi_service_account_result.rc == 0
